name: Hellow World Workflow
on:
  push
    branches:
        - main
  pull_request:
     branches:
        - main

  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: echo "Hellow World"
       run: echo "Hello Workd"
       shell: bash
  
  goodbye:
     runs-on: ubuntu-latest
     steps:
       - name: goodbye world
         run: echo "Goodbye World"
        shell: bash
